"""Written content for each sample listing, keyed by title.

Follows Airbnb's "About this space" layout: a short summary shown on the page,
then "The space", "Guest access" and "Other things to note" in the Show more dialog.
"sleep" is one entry per bedroom for the "Where you'll sleep" section; its bed
counts must add up to the listing's number of beds (seed.py checks this).
"""

LISTING_TEXT: dict[str, dict] = {
    "Beachfront villa with private pool": {
        "summary": "A four-bedroom villa right behind Candolim's dunes, with a private pool, a shaded sit-out and the sea a two-minute walk away.\n\nIt is big enough for two families or a group of friends, close to the restaurants of Candolim and Calangute but quiet once the gate is shut.",
        "space": "The ground floor is one open living and dining area that opens straight onto the pool deck. Sliding doors stay open most of the day, so the sea breeze moves through the whole house.\n\nThe kitchen is fully equipped for proper cooking, with a large fridge, a gas hob, an oven and a breakfast counter. Our caretaker can arrange a cook for Goan meals on request.\n\nUpstairs, two of the bedrooms have balconies facing the palms. Every bedroom has its own bathroom, air conditioning and blackout curtains for slow beach mornings.",
        "guest_access": "Guests have the entire villa, pool and garden to themselves. The caretaker lives in a separate cottage at the back of the property.",
        "other_notes": "The pool is not fenced, so please keep an eye on young children. Loud music outdoors must stop by 10 PM as per local rules.",
        "sleep": ["1 king bed", "1 king bed", "1 queen bed", "2 single beds"],
    },
    "Cozy studio steps from Anjuna beach": {
        "summary": "A bright studio on a quiet lane, three minutes on foot from Anjuna beach and the Wednesday flea market.\n\nMade for couples and solo travellers who want to spend their days outside and come back to a clean, cool room.",
        "space": "The studio has a comfortable queen bed, a small sofa, a writing table and a kitchenette with a two-burner stove, kettle and fridge.\n\nThe bathroom has a hot water shower. A small balcony looks onto the neighbour's coconut trees and catches the evening light.",
        "guest_access": "You have the whole studio. It is on the first floor of a small building, reached by an outside staircase.",
        "other_notes": "Anjuna gets lively on weekends during the season. Earplugs are in the bedside drawer if you are a light sleeper.",
        "sleep": ["1 queen bed"],
    },
    "Portuguese heritage home in Fontainhas": {
        "summary": "A 120-year-old Portuguese home in the Latin quarter of Panaji, with its original oyster-shell windows, red oxide floors and a balcao for evening chai.\n\nWalk to the Mandovi riverfront, the old chapels and some of the best Goan restaurants in the city.",
        "space": "The house has been carefully restored. High wooden ceilings keep the rooms cool, and the furniture is a mix of family antiques and comfortable modern pieces.\n\nThe living room leads to a small inner courtyard with a frangipani tree. The dining table seats six, and the kitchen is fully stocked.\n\nAll three bedrooms are upstairs, each with its own bathroom. The front bedroom opens onto a balcony over the painted street.",
        "guest_access": "Guests have the entire house. The street is pedestrian-friendly, and parking is available at the public lot two minutes away.",
        "other_notes": "As a heritage building the stairs are steep and narrow. Please don't hang anything on the old walls.",
        "sleep": ["1 queen bed", "1 double bed", "1 double bed"],
    },
    "Palolem beach hut with sea view": {
        "summary": "A simple, well-kept wooden hut on the edge of Palolem's crescent beach, with a hammock on the porch and the sea in front of you.\n\nPerfect for switching off. Fall asleep to the waves and wake up early for a swim in calm water.",
        "space": "The hut is built from local wood and bamboo, raised on stilts above the sand. Inside is a double bed with a mosquito net, a fan, a small wardrobe and reading lights.\n\nThe attached bathroom is open to the sky at the back, with a hot water shower. The porch has a hammock and two chairs for sunsets.",
        "guest_access": "The hut is yours. Our beach cafe next door serves breakfast and fresh juice from 8 AM.",
        "other_notes": "Huts are open from October to May only. There is no air conditioning, but the sea breeze keeps it cool at night.",
        "sleep": ["1 double bed"],
    },
    "Lakeside cottage on the Vembanad backwaters": {
        "summary": "A Kerala-style cottage with a sloping tiled roof, sitting right on the edge of Vembanad Lake in Kumarakom.\n\nWatch fishing canoes pass from the verandah, take a country boat out through the canals, and end the day with a home-cooked Kerala meal.",
        "space": "The cottage has a long front verandah facing the water, a living room with carved wooden furniture and two airy bedrooms with attached bathrooms.\n\nOur family lives in the main house next door and cooks breakfast every morning. Lunch and dinner can be arranged too: think karimeen fry, appam and fish curry.",
        "guest_access": "Guests have the whole cottage, the lawn and the private jetty. Canoe rides can be booked with us.",
        "other_notes": "Mosquito nets and repellent are provided. During the monsoon (June to August) the lake level rises and some walking paths close.",
        "sleep": ["1 king bed", "1 queen bed"],
    },
    "Tea estate bungalow with valley views": {
        "summary": "A planter's bungalow on a working tea estate above Munnar, surrounded by green slopes and misty valleys.\n\nMornings start with estate-grown tea on the lawn. Spend the day on plantation walks or drive up to Eravikulam National Park.",
        "space": "The bungalow was built in the 1940s and keeps its fireplace, wooden floors and big bay windows over the valley.\n\nThere is a large living room, a dining room seating eight and a sunny glass-fronted verandah. The cook prepares Kerala and continental meals.\n\nThe three bedrooms each have attached bathrooms with hot water. The master bedroom has a king bed facing the valley, and the family room has two single beds for kids.",
        "guest_access": "Guests have the full bungalow and its garden. A guided walk through the tea estate and factory is included.",
        "other_notes": "Nights get cold between November and February, so pack a jacket. The last 3 km of road is narrow and winding.",
        "sleep": ["1 king bed", "1 queen bed", "2 single beds"],
    },
    "Cliffside room overlooking Varkala beach": {
        "summary": "A sea-view room on Varkala's north cliff, with a private balcony looking straight out over the Arabian Sea.\n\nThe cliff path with its cafes and yoga studios is right outside, and steps lead down to the beach.",
        "space": "The room has a queen bed, a reading chair and big windows on two sides. The balcony is the best part: sunsets here are spectacular.\n\nThe bathroom has a rain shower and hot water. There is a kettle with tea and coffee, and a small fridge.",
        "guest_access": "You have your own room, balcony and bathroom in our small family guesthouse. The rooftop is shared with the other two rooms.",
        "other_notes": "The cliff edge has no railing in places, so take care at night. The beach has strong currents; swim only between the flags.",
        "sleep": ["1 queen bed"],
    },
    "Traditional tharavad in Fort Kochi": {
        "summary": "Stay in a restored Kerala tharavad with a central nadumuttam courtyard, carved wooden ceilings and cool red-oxide floors.\n\nIt is a short walk to the Chinese fishing nets, Jew Town and the cafes of Fort Kochi.",
        "space": "The house is built around an open courtyard that lets in light and rain. Around it are the living room, a dining area and the kitchen.\n\nBoth bedrooms have teak four-poster beds and attached bathrooms. The second bedroom also has a single bed, which works well for a child or a third adult.\n\nThe back verandah opens onto a small garden with mango and banana trees.",
        "guest_access": "The whole house is yours. We live five minutes away and drop by each morning to check you have everything.",
        "other_notes": "Old houses have their quirks: the doors are low, so mind your head. Bicycles are available to explore Fort Kochi.",
        "sleep": ["1 queen bed", "1 double bed, 1 single bed"],
    },
    "Pine wood cabin with mountain views": {
        "summary": "A pine wood cabin above Manali, facing snow peaks and a forest of deodars.\n\nWarm, quiet and a short drive from Mall Road, it is a great base for Solang Valley, Rohtang and long walks in the woods.",
        "space": "The cabin is built entirely of pine, with a wood-burning stove in the living room and big windows facing the mountains.\n\nThere is a small kitchen for simple meals, and our caretaker can cook Himachali dishes on request.\n\nThe main bedroom is downstairs and the second, cosy attic bedroom is up a wooden ladder-staircase. The bathroom has a geyser for hot water.",
        "guest_access": "The whole cabin and the front deck are yours. Parking is available for one car at the bottom of the path.",
        "other_notes": "Expect a 3-minute uphill walk from the parking spot to the cabin. Snow chains are needed in winter.",
        "sleep": ["1 queen bed", "1 double bed"],
    },
    "Apple orchard cottage in Old Manali": {
        "summary": "A stone and wood cottage in the middle of our family's apple orchard in Old Manali.\n\nPick apples in season, sit under the trees with a book, and walk to the cafes of Old Manali in ten minutes.",
        "space": "The cottage is one large room with a queen bed and a single bed, a seating corner by the window and a small kitchenette.\n\nThe bathroom has a hot water shower. Outside, a small sit-out looks over the orchard to the snow peaks.",
        "guest_access": "You have the cottage and free run of the orchard. We live in the main house on the same land.",
        "other_notes": "Apple season is August to October. The path from the road is unpaved and gets muddy when it rains.",
        "sleep": ["1 queen bed, 1 single bed"],
    },
    "Himalayan A-frame by the Parvati river": {
        "summary": "A small A-frame cabin on the banks of the Parvati river, a short walk from Kasol market.\n\nFall asleep to the sound of the river, and spend your days trekking to Kheerganga, Tosh or Chalal.",
        "space": "The A-frame has a double bed under the sloping roof, a single bed by the window and a small sitting area with a heater.\n\nThe bathroom is attached with a geyser. The front deck sits right above the river, with two chairs and a small fire pit.",
        "guest_access": "You have the whole cabin and deck. The cafe at the front of the property serves Israeli and Himachali food.",
        "other_notes": "Mobile network in Kasol is patchy; Wi-Fi works best in the cafe. The river is fast and cold, so don't swim in it.",
        "sleep": ["1 double bed, 1 single bed"],
    },
    "Colonial cottage near the Shimla ridge": {
        "summary": "A British-era cottage just below the Ridge, with sloping tin roofs, wooden floors and views over the hills of Shimla.\n\nWalk to Mall Road, Christ Church and Jakhoo temple, then come back to a fire and a pot of tea.",
        "space": "The cottage has a cosy living room with a fireplace, a dining area and a kitchen with everything you need.\n\nBoth bedrooms have attached bathrooms and heaters. The front verandah has a long bench and a view that changes with the clouds.",
        "guest_access": "The whole cottage and the small front garden are yours.",
        "other_notes": "Cars are not allowed near the Ridge; the cottage is a 10-minute walk from the nearest drop point. Porters can carry your bags.",
        "sleep": ["1 king bed", "1 queen bed"],
    },
    "Riverside retreat near Rishikesh": {
        "summary": "A calm, plant-filled guesthouse above the Ganga, 15 minutes from Laxman Jhula.\n\nBegin the day with yoga on the terrace, raft the rapids in the afternoon and watch the Ganga aarti in the evening.",
        "space": "The retreat has two bedrooms, a living room with floor seating and a large terrace facing the river and forest.\n\nThe kitchen serves simple vegetarian meals, and fresh fruit and herbal tea are always on the table.\n\nBoth bedrooms have attached bathrooms with hot water and views of the hills.",
        "guest_access": "Guests have the whole first floor and the terrace. Morning yoga with our in-house teacher is included.",
        "other_notes": "Rishikesh is a vegetarian, alcohol-free town, and we ask guests to respect that here too.",
        "sleep": ["1 queen bed", "1 queen bed"],
    },
    "Lake-view home in Nainital": {
        "summary": "A family home on the slopes above Naini Lake, with views over the water from the living room and both bedrooms.\n\nWalk down to the Mall Road and the boat club, or drive to Snow View and Tiffin Top.",
        "space": "The living room has a wall of windows over the lake and a fireplace for chilly evenings.\n\nThere is a fully equipped kitchen and a dining table for six. Both bedrooms have attached bathrooms; the second bedroom has an extra single bed for a child.\n\nA small balcony is the best place for morning tea as the mist lifts off the lake.",
        "guest_access": "Guests have the whole house. A covered parking spot is available.",
        "other_notes": "There are about 40 steps from the road down to the house. Heaters are provided in winter.",
        "sleep": ["1 king bed", "1 double bed, 1 single bed"],
    },
    "Forest cabin in Mukteshwar": {
        "summary": "A stone and timber cabin in an oak and rhododendron forest, with a clear view of the Himalayan range on sunny days.\n\nIdeal for birdwatching, forest walks and quiet days with a book.",
        "space": "The cabin has a living room with a wood stove, two bedrooms with attached bathrooms and a glass-walled dining area facing the peaks.\n\nOur cook makes simple Kumaoni meals with vegetables from our garden.\n\nThe deck wraps around the cabin and is perfect for watching the sunrise light up Trishul and Nanda Devi.",
        "guest_access": "Guests have the entire cabin, the deck and the forest trail that starts at the gate.",
        "other_notes": "Power cuts happen in the hills; we have an inverter for lights and Wi-Fi. Leopards live in this forest, so don't walk the trail after dark.",
        "sleep": ["1 queen bed", "1 queen bed"],
    },
    "Haveli suite in the Pink City": {
        "summary": "A royal suite in an 18th-century haveli in Jaipur's old city, with painted walls, jharokha windows and a rooftop over the pink bazaars.\n\nHawa Mahal, City Palace and Johari Bazaar are all within walking distance.",
        "space": "The suite has a carved king bed, a separate single bed and a sitting area with low cushions by the jharokha window.\n\nThe bathroom is modern, with a rain shower. Breakfast is served in the courtyard, and the rooftop restaurant has views of Nahargarh Fort.",
        "guest_access": "You have a private suite in a heritage guesthouse. The courtyard, rooftop and library are shared with other guests.",
        "other_notes": "The old city lanes are narrow; we'll send an e-rickshaw to meet your taxi at the main road.",
        "sleep": ["1 king bed, 1 single bed"],
    },
    "Lake Pichola view heritage room": {
        "summary": "A heritage room with a window seat right over Lake Pichola, looking across to the City Palace.\n\nAt night the palace and Jag Mandir light up in front of you.",
        "space": "The room has a queen bed, an arched window seat with cushions and traditional Mewari paintings on the walls.\n\nThe bathroom has hot water and a rain shower. A small balcony hangs over the water.",
        "guest_access": "You have a private room in our family haveli. The rooftop cafe is shared with other guests.",
        "other_notes": "The ghat outside gets busy during festivals like Gangaur. A boat ride from our private jetty can be booked.",
        "sleep": ["1 queen bed"],
    },
    "Desert villa with pool near the dunes": {
        "summary": "A golden sandstone villa on the edge of the Thar, with a private pool and the dunes at Sam a short drive away.\n\nSpend the day on a camel safari, then cool off in the pool and eat under the stars.",
        "space": "The villa is built from local Jaisalmer stone around a central courtyard and pool. The living room has jharokha windows and low seating.\n\nThe kitchen and dining room open onto the courtyard. Our chef cooks Rajasthani thalis and barbecue dinners.\n\nAll three bedrooms have attached bathrooms with rain showers. The rooftop terrace is great for stargazing.",
        "guest_access": "Guests have the entire villa, the pool and the rooftop. A jeep and camel safari can be arranged.",
        "other_notes": "Days are very hot from April to June. In winter, nights can drop below 10°C, and the pool is not heated.",
        "sleep": ["1 king bed", "1 king bed", "1 queen bed"],
    },
    "Rooftop studio near Hawa Mahal": {
        "summary": "A small, bright studio on a rooftop in the old city, five minutes on foot from Hawa Mahal.\n\nThe private terrace looks over Jaipur's pink rooftops and the Nahargarh hills.",
        "space": "The studio has a queen bed, a work desk, a compact kitchenette and air conditioning.\n\nThe bathroom has a hot water shower. The terrace has a swing and plants, and is perfect for evening chai and kite-watching.",
        "guest_access": "The studio and its terrace are yours. It is on the fourth floor, with no lift.",
        "other_notes": "The bazaar below is busy and noisy during the day but quiet at night.",
        "sleep": ["1 queen bed"],
    },
    "Sea-facing apartment in Bandra": {
        "summary": "A two-bedroom apartment on Bandra's Carter Road, with the sea right outside the living room windows.\n\nWalk along the promenade, eat your way through Bandra's cafes and get anywhere in Mumbai with the station close by.",
        "space": "The living room faces the Arabian Sea and has a large sofa, a dining table for four and a smart TV.\n\nThe kitchen is fully equipped, and the apartment has a washing machine and a dedicated work desk with fast Wi-Fi.\n\nThe master bedroom has a sea view and attached bathroom; the second bedroom has its own bathroom too.",
        "guest_access": "You have the entire apartment. The building has a lift, a watchman and one parking spot.",
        "other_notes": "Building rules: no parties, and visitors must sign in at the gate. The monsoon views here are spectacular.",
        "sleep": ["1 king bed", "1 queen bed"],
    },
    "Art deco flat in Colaba": {
        "summary": "A high-ceilinged flat in a 1930s art deco building in Colaba, minutes from the Gateway of India and Kala Ghoda.\n\nOld Bombay charm, walking distance from galleries, museums and Leopold Cafe.",
        "space": "The flat has original art deco details, tall windows, a living room with a vintage sofa and a writing desk.\n\nThe bedroom has a queen bed, and a daybed in the study works as a single bed. The kitchen is small but well equipped.",
        "guest_access": "The whole flat is yours. It is on the second floor with an old-style cage lift.",
        "other_notes": "Street parking in Colaba is hard to find; taxis are the easiest way around.",
        "sleep": ["1 queen bed, 1 single bed"],
    },
    "Modern loft in Indiranagar": {
        "summary": "A modern loft on a quiet street off 12th Main, Indiranagar, close to Bengaluru's best breweries and restaurants.\n\nIdeal for work trips, with fast Wi-Fi, a proper desk and the metro a 10-minute walk away.",
        "space": "Downstairs is an open living room, a work corner and a kitchen with a coffee machine. Upstairs, the mezzanine bedroom has a queen bed and a single bed.\n\nThe bathroom has a walk-in rain shower. The flat gets lovely afternoon light.",
        "guest_access": "You have the entire loft. Self check-in with a keypad lock.",
        "other_notes": "The mezzanine stairs are steep and have no railing on one side; not ideal for small children.",
        "sleep": ["1 queen bed, 1 single bed"],
    },
    "Garden home in Lutyens' Delhi": {
        "summary": "A spacious bungalow in the heart of Lutyens' Delhi, with a large lawn shaded by old neem trees.\n\nKhan Market, Lodhi Garden and India Gate are minutes away.",
        "space": "The house has a formal living room, a family room with a TV, a dining room for eight and a large kitchen.\n\nThe three bedrooms all have attached bathrooms. The master bedroom opens onto the garden, and the third bedroom has two single beds.\n\nBreakfast is served on the verandah by our staff.",
        "guest_access": "Guests have the entire house and lawn. Our staff live in separate quarters on the property.",
        "other_notes": "Delhi winters can be smoggy; air purifiers are in every bedroom. Two parking spots are available inside the gate.",
        "sleep": ["1 king bed", "1 queen bed", "2 single beds"],
    },
    "Boutique stay in Hauz Khas Village": {
        "summary": "A boutique studio in Hauz Khas Village, overlooking the deer park and the 13th-century lake and ruins.\n\nStep out to art galleries, design stores and rooftop cafes.",
        "space": "The studio has a queen bed, a reading corner and a kitchenette, with handmade furniture and local art on the walls.\n\nThe bathroom has a rain shower. A small balcony looks over the lake.",
        "guest_access": "You have the whole studio. It is on the third floor, with no lift.",
        "other_notes": "Hauz Khas Village gets crowded on weekend nights. Cars can't enter the village lanes.",
        "sleep": ["1 queen bed"],
    },
    "Coffee estate villa in Coorg": {
        "summary": "A four-bedroom villa in the middle of a 40-acre coffee and pepper estate near Madikeri.\n\nWake up to birdsong and fresh estate coffee, walk the plantation trails and visit Abbey Falls.",
        "space": "The villa has a large living room with a fireplace, a long dining table and a wraparound verandah overlooking the coffee bushes.\n\nOur cook makes traditional Kodava food, including pandi curry and akki roti.\n\nAll four bedrooms have attached bathrooms. The kids' room has two single beds, and the master bedroom has a private balcony.",
        "guest_access": "Guests have the whole villa and the estate trails. A plantation tour with the estate manager is included.",
        "other_notes": "Leeches come out in the monsoon; we provide leech socks for walks. The road in is unpaved for the last 2 km.",
        "sleep": ["1 king bed", "1 queen bed", "1 queen bed", "2 single beds"],
    },
    "Infinity pool villa near Lonavala": {
        "summary": "A five-bedroom villa on a hilltop near Lonavala, with an infinity pool looking out over the Sahyadri hills.\n\nAn easy drive from Mumbai and Pune, it is made for big family weekends and celebrations.",
        "space": "The double-height living room opens onto the pool deck and lawn. There is a games room with a pool table and a large dining area.\n\nThe chef's kitchen is fully equipped, and our cook can prepare Maharashtrian or continental meals.\n\nAll five bedrooms have attached bathrooms, and three have balconies facing the valley. The last bedroom has two single beds for kids.",
        "guest_access": "Guests have the entire villa, pool, lawn and barbecue area.",
        "other_notes": "The pool is 6 feet deep at one end and has no lifeguard. Music must be turned down after 10 PM.",
        "sleep": ["1 king bed", "1 king bed", "1 queen bed", "1 queen bed", "2 single beds"],
    },
    "Farmhouse with pool in Alibaug": {
        "summary": "A whitewashed farmhouse among mango and coconut trees in Alibaug, with a private pool and a big green lawn.\n\nTake the ferry from Mumbai, and you'll be at the pool in under two hours.",
        "space": "The farmhouse has a large living room that opens onto the pool, a dining area seating ten and a fully equipped kitchen.\n\nThe four bedrooms all have attached bathrooms. Two are on the ground floor, which is handy for older guests.\n\nOur caretaker can cook fresh seafood from the local market.",
        "guest_access": "Guests have the whole farmhouse, the pool and the orchard.",
        "other_notes": "Kihim and Varsoli beaches are 10 minutes away by car. Mosquito repellent is provided.",
        "sleep": ["1 king bed", "1 queen bed", "1 queen bed", "1 queen bed"],
    },
    "French Quarter heritage home": {
        "summary": "A yellow-walled colonial home in Puducherry's French Quarter, with arched doorways, a bougainvillea courtyard and a rooftop terrace.\n\nThe Promenade and the best bakeries in town are a five-minute walk away.",
        "space": "The house mixes French colonial architecture with Tamil design: high ceilings, Athangudi tile floors and teak furniture.\n\nThe ground floor has a living room, dining room and kitchen around the courtyard. The three bedrooms are upstairs, each with an attached bathroom.\n\nThe rooftop terrace is perfect for breakfast with a view of the old town.",
        "guest_access": "Guests have the whole house and terrace. Bicycles are available for exploring.",
        "other_notes": "The French Quarter has strict parking rules; we'll guide you to the nearest lot.",
        "sleep": ["1 king bed", "1 queen bed", "1 double bed"],
    },
    "Beach cottage near Auroville": {
        "summary": "A thatched-roof cottage set in a garden near Auroville, a short walk from a quiet beach.\n\nCycle to the Matrimandir, eat at Auroville's cafes and come back to the sound of the sea.",
        "space": "The cottage is built with natural materials, with a terracotta floor and a high thatched roof that keeps it cool.\n\nIt has a queen bed and a single bed, a sitting area and a small kitchenette. The open-air bathroom has a garden view.",
        "guest_access": "You have the whole cottage and its garden. The beach path starts at our back gate.",
        "other_notes": "We follow Auroville's eco practices: please keep showers short and switch off lights when you go out.",
        "sleep": ["1 queen bed, 1 single bed"],
    },
    "Houseboat stay on Dal Lake": {
        "summary": "A traditional cedar-wood houseboat on Dal Lake, with carved ceilings, Kashmiri carpets and a front deck right on the water.\n\nTake a shikara to the floating market at dawn and watch the Zabarwan hills change colour at sunset.",
        "space": "The houseboat has a carved living room, a dining room and two bedrooms, each with an attached bathroom.\n\nOur family serves Kashmiri breakfast and dinner on board, including kahwa, wazwan dishes and fresh bread from the local baker.\n\nThe front deck is the best place to spend the evening.",
        "guest_access": "You have the whole houseboat. A shikara takes you to and from the shore at any time.",
        "other_notes": "The houseboat is heated in winter. Please wear the life jacket provided on shikara rides.",
        "sleep": ["1 king bed", "1 queen bed"],
    },
    "Tea garden cottage in Darjeeling": {
        "summary": "A cottage in a tea garden on the slopes below Darjeeling, facing Kanchenjunga on clear mornings.\n\nTaste first-flush tea at the estate, ride the toy train and walk to Tiger Hill for sunrise.",
        "space": "The cottage has a living room with a fireplace, a small dining area and big windows facing the mountains.\n\nBoth bedrooms have heaters and thick quilts. They share one bathroom with a hot water shower.\n\nOur caretaker cooks Nepali and Tibetan dishes on request.",
        "guest_access": "Guests have the whole cottage and garden. A tea tasting at the estate factory is included.",
        "other_notes": "The cottage is 30 minutes from Darjeeling town by car. Kanchenjunga is clearest from October to December.",
        "sleep": ["1 queen bed", "1 double bed"],
    },
    "Cliffside villa with plunge pool": {
        "summary": "A modern villa on the cliffs above Gokarna's Om Beach, with a plunge pool facing the sea.\n\nWalk the coastal trail to Half Moon and Paradise beach, then come back for sunset by the pool.",
        "space": "The villa is built in laterite stone with large glass doors that open onto the pool deck and the sea view.\n\nThe living room, dining area and kitchen are open plan. Our caretaker can cook coastal Karnataka meals.\n\nAll three bedrooms have attached bathrooms; two of them face the sea.",
        "guest_access": "Guests have the entire villa, pool and garden. A path leads down to the beach in about ten minutes.",
        "other_notes": "The path to the beach is steep and rocky, so wear proper footwear. The sea is rough in the monsoon.",
        "sleep": ["1 king bed", "1 queen bed", "1 queen bed"],
    },
}
